/* FS5 Live Scores */
.live-main{padding:clamp(22px,4vw,46px) 0 34px;background:linear-gradient(180deg,#f5f8fb 0%,#fff 42%)}
.live-shell{width:min(1180px,92%);margin:0 auto}.live-hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;padding:clamp(24px,4vw,42px);margin-bottom:22px;color:#fff;background:linear-gradient(135deg,#00376b,#0b527f);border-radius:18px;box-shadow:0 14px 36px rgba(0,55,107,.18)}
.live-kicker,.section-kicker{margin:0 0 7px;font-size:.75rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase;opacity:.78}.live-hero h1{margin:0;font-size:clamp(2rem,5vw,3.25rem);line-height:1}.live-subtitle{margin:12px 0 0;max-width:680px;font-size:clamp(.95rem,2vw,1.08rem);opacity:.9}.live-status{padding:10px 13px;border:1px solid rgba(255,255,255,.22);border-radius:999px;font-size:.82rem;font-weight:700;white-space:nowrap;background:rgba(255,255,255,.08)}.live-status.is-live{background:rgba(38,180,104,.2)}.live-status.is-error{background:rgba(180,38,38,.2)}
.week-toolbar{display:flex;align-items:end;gap:16px;flex-wrap:wrap;margin:0 0 22px;padding:17px 20px;background:#fff;border:1px solid #dce5ee;border-radius:14px;box-shadow:0 5px 18px rgba(16,44,70,.06)}.week-control{display:flex;flex-direction:column;gap:6px}.week-control label{font-size:.74rem;font-weight:800;color:#4a5a69;text-transform:uppercase;letter-spacing:.08em}.week-control select{min-width:150px;padding:10px 12px;border:1px solid #b9c8d6;border-radius:8px;background:#fff;color:#0c2f4d;font-weight:700}.week-context{flex:1;min-width:200px;color:#526475;font-size:.92rem;padding-bottom:10px}.refresh-button{padding:10px 15px;border:1px solid #00376b;border-radius:8px;background:#00376b;color:#fff;font-weight:800;cursor:pointer}.refresh-button:hover{background:#0b527f}
.scoreboard{background:#fff;border:1px solid #dce5ee;border-radius:16px;padding:clamp(18px,3vw,28px);box-shadow:0 8px 24px rgba(16,44,70,.07)}.section-heading{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:18px}.section-kicker{color:#527087}.section-heading h2{margin:0;color:#0c2f4d;font-size:clamp(1.35rem,3vw,2rem)}.section-badge{display:inline-flex;align-items:center;justify-content:center;min-width:74px;padding:8px 12px;border-radius:999px;background:#eaf3f9;color:#00376b;font-weight:900}
.matchup-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.matchup-card{border:1px solid #d7e1ea;border-radius:14px;overflow:hidden;background:#fff}.matchup-card__head{display:flex;justify-content:space-between;align-items:center;padding:10px 14px;background:#f3f7fa;border-bottom:1px solid #e0e7ed}.matchup-card__label{font-size:.72rem;font-weight:800;color:#5a6e7e;text-transform:uppercase;letter-spacing:.08em}.matchup-card__state{font-size:.7rem;font-weight:900;color:#496170}.matchup-card__state.is-current{color:#12804a}
.matchup-team{padding:15px 16px;background:#fff}.matchup-team.is-winning{background:#fbfdff}.team-top{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px}.team-avatar{width:48px;height:48px;border-radius:12px;object-fit:cover;background:#e8eef3;border:1px solid #d5e0e8}.team-name{margin:0;color:#0c2f4d;font-size:1rem;font-weight:850;overflow-wrap:anywhere}.sleeper-name{margin:3px 0 0;color:#738391;font-size:.76rem;overflow-wrap:anywhere}.team-score{color:#0c2f4d;font-size:clamp(1.45rem,3vw,1.9rem);font-weight:900;font-variant-numeric:tabular-nums;text-align:right}.matchup-team.is-winning .team-score{color:#00376b}.leading{margin-top:3px;text-align:right;font-size:.68rem;font-weight:800;color:#12804a}.vs-divider{text-align:center;margin:-6px 0 -6px;position:relative;z-index:2}.vs-divider span{display:inline-flex;min-width:28px;height:28px;align-items:center;justify-content:center;border-radius:50%;background:#00376b;color:#fff;font-size:.65rem;font-weight:900;border:3px solid #fff}
.predictor{margin:12px 0 0;padding:11px 12px;border:1px solid #dce5ee;border-radius:10px;background:#f8fafc}.predictor__top{display:flex;justify-content:space-between;gap:12px;align-items:center}.predictor__title{font-size:.72rem;font-weight:900;color:#526475;text-transform:uppercase;letter-spacing:.07em}.predictor__winner{font-size:.84rem;font-weight:900;color:#0c2f4d;text-align:right}.predictor__bar{height:9px;margin-top:8px;display:flex;overflow:hidden;border-radius:999px;background:#dce5ee}.predictor__a,.predictor__b{height:100%}.predictor__a{background:#00376b}.predictor__b{background:#8ca8bb}.predictor__labels{display:flex;justify-content:space-between;margin-top:5px;color:#647786;font-size:.67rem;font-weight:800}
.lineups{border-top:1px solid #e7edf2;margin-top:13px;padding-top:10px}.lineup-toggle{width:100%;display:flex;justify-content:space-between;align-items:center;border:0;background:none;padding:5px 0;color:#0c2f4d;font-weight:850;cursor:pointer;text-align:left}.lineup-toggle::after{content:'+';font-size:1.1rem}.lineup-toggle[aria-expanded="true"]::after{content:'−'}.lineup-content{display:none;padding:4px 0 2px}.lineup-content.is-open{display:block}.lineup-group-title{margin:8px 0 5px;color:#728493;font-size:.68rem;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.player-row{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:8px;align-items:center;padding:6px 0;border-bottom:1px solid #eef2f5;font-size:.8rem}.player-row:last-child{border-bottom:0}.player-pos{font-size:.65rem;font-weight:900;color:#607384}.player-name{color:#263f52;font-weight:750}.player-nfl{color:#82919c;font-size:.68rem}.player-points{font-variant-numeric:tabular-nums;color:#425d70;font-weight:800}
.empty-state{padding:40px 18px;text-align:center;color:#657786;border:1px dashed #cbd7e1;border-radius:12px;background:#f9fbfc}.source-note{margin:16px 3px 0;color:#6b7d8c;font-size:.78rem;line-height:1.5}.source-note strong{color:#425b6d}
@media(max-width:760px){.live-hero{align-items:flex-start;flex-direction:column}.live-status{white-space:normal}.week-toolbar{align-items:stretch}.week-context{padding:0}.refresh-button{align-self:flex-start}.matchup-grid{grid-template-columns:1fr}.team-top{grid-template-columns:auto minmax(0,1fr) auto}.team-avatar{width:42px;height:42px}.player-row{grid-template-columns:38px minmax(0,1fr) auto}}
