(function(){
"use strict";
const LEAGUE_ID="1387297022695993344", SEASON=2026, REFRESH_MS=45000;
const BASE="https://api.sleeper.app/v1", DATA_BASE="https://api.sleeper.com/v1";
const S={week:null,selected:null,league:null,rosters:[],users:[],players:{},stats:{},projections:{},schedule:[],matchups:[],scoring:{},teamMap:new Map()};
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async path=>{const r=await fetch(BASE+path,{cache:"no-store",headers:{"Accept":"application/json"}});if(!r.ok)throw Error("Sleeper API "+r.status);return r.json();};
const dataApi=async path=>{const r=await fetch(DATA_BASE+path,{cache:"no-store",headers:{"Accept":"application/json"}});if(!r.ok)throw Error("Sleeper data API "+r.status);return r.json();};
const cdn=(id,thumb=false)=>id?`https://sleepercdn.com/avatars/${thumb?'thumbs/':''}${encodeURIComponent(id)}`:"";
const pimg=id=>id?`https://sleepercdn.com/content/nfl/players/thumb/${encodeURIComponent(id)}.jpg`:"";
const n=v=>Number.isFinite(Number(v))?Number(v):0, fmt=v=>n(v).toFixed(2), norm=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
function scoreStats(stats){let total=0;for(const [k,val] of Object.entries(stats||{})){const rate=n(S.scoring[k]);if(rate&&Number.isFinite(Number(val)))total+=rate*Number(val);}return total;}
function teamInfo(roster){return S.teamMap.get(String(roster.roster_id))||{};}
function teamName(user){return user?.metadata?.team_name||user?.metadata?.team_name?.trim()||user?.display_name||user?.username||"FS5 Team";}
function avatar(user){return user?.avatar?cdn(user.avatar):"/artwork/logo.png";}
function buildTeams(){const users=new Map(S.users.map(u=>[String(u.user_id),u]));S.teamMap=new Map();for(const r of S.rosters){const u=users.get(String(r.owner_id))||{};S.teamMap.set(String(r.roster_id),{roster:r,user:u,teamName:teamName(u),account:u.username?"@"+u.username:u.display_name||"",avatar:avatar(u),record:{wins:n(r.settings?.wins),losses:n(r.settings?.losses),ties:n(r.settings?.ties),pf:n(r.settings?.fpts)+n(r.settings?.fpts_decimal)/100,pa:n(r.settings?.fpts_against)+n(r.settings?.fpts_against_decimal)/100}});}}
function rankTeams(){const arr=[...S.teamMap.entries()].map(([id,t])=>({id,t}));const vals={pf:arr.map(x=>x.t.record.pf),diff:arr.map(x=>x.t.record.pf-x.t.record.pa)};const pct=(v,a)=>{const lo=Math.min(...a),hi=Math.max(...a);return hi===lo?50:50+50*(v-lo)/(hi-lo)};return arr.map(x=>{const games=x.t.record.wins+x.t.record.losses+x.t.record.ties;const wr=games?(x.t.record.wins+.5*x.t.record.ties)/games:.5;const ps=100*wr;const pfs=pct(x.t.record.pf,vals.pf), ds=pct(x.t.record.pf-x.t.record.pa,vals.diff);return {...x,score:.5*ps+.3*pfs+.2*ds,wr,pfs,ds};}).sort((a,b)=>b.score-a.score);}
function renderRanks(){const el=$("power-ranking-list"), ranks=rankTeams();el.innerHTML=ranks.map((x,i)=>`<div class="power-row"><div class="power-rank">${i+1}</div><img class="power-avatar" src="${esc(x.t.avatar)}" alt="" loading="lazy" onerror="this.src='/artwork/logo.png'"><div class="power-team"><strong>${esc(x.t.teamName)}</strong><span>${esc(x.t.account)} · ${x.t.record.wins}-${x.t.record.losses}-${x.t.record.ties} · ${fmt(x.t.record.pf)} PF</span></div><div class="power-score"><b>${x.score.toFixed(1)}</b><small>Power</small></div></div>`).join("")||'<div class="empty-state">No team data.</div>';}
function projectionFor(id){return scoreStats(S.projections[id]);}
function currentFor(id){return scoreStats(S.stats[id]);}
function player(id){return S.players[id]||{player_id:id,first_name:id,last_name:"",position:"",fantasy_positions:[]};}
function playerRow(id,starter){const p=player(id), cur=currentFor(id), proj=projectionFor(id);return `<button class="player-row ${starter?'is-starter':'is-bench'}" data-player="${esc(id)}"><img src="${esc(pimg(id))}" alt="" loading="lazy" onerror="this.style.visibility='hidden'"><span class="player-main"><strong>${esc((p.first_name||"")+" "+(p.last_name||""))}</strong><small>${esc(p.position||p.fantasy_positions?.[0]||"")} · ${esc(p.team||"")} ${p.injury_status?"· "+esc(p.injury_status):""}</small></span><span class="player-points"><b>${fmt(cur)}</b><small>${fmt(proj)} proj</small></span></button>`;}
function gameStatus(teamAbbr){const games=S.schedule.filter(g=>g.home===teamAbbr||g.away===teamAbbr);return games.find(g=>g.status==="in_game")?.status||games.find(g=>g.status==="complete")?.status||games[0]?.status||"pre_game";}
function teamProjected(roster,matchup){const ids=matchup.players||roster.players||[];let current=0,remaining=0,variance=0;for(const id of ids){const c=currentFor(id), pr=projectionFor(id);if((matchup.starters||[]).includes(id)){current+=c;const stat=S.stats[id];if(stat&&Object.keys(stat).length){const rem=Math.max(0,pr-c);remaining+=rem;variance+=Math.max(1,rem*.28)**2}else{remaining+=pr;variance+=Math.max(1,pr*.28)**2}}}return {current,projected:current+remaining,variance};}
function winProb(a,b){const diff=a.projected-b.projected, sd=Math.sqrt(a.variance+b.variance)||1;let p=.5*(1+erf(diff/(sd*Math.sqrt(2))));return Math.min(.995,Math.max(.005,p));}
function erf(x){const s=x<0?-1:1;x=Math.abs(x);const t=1/(1+.3275911*x),a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429;return s*(1-((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t*Math.exp(-x*x));}
function probBar(p){return `<div class="prob-wrap"><div class="prob-labels"><b>${(p*100).toFixed(0)}%</b><span>FS5 projected win probability</span><b>${((1-p)*100).toFixed(0)}%</b></div><div class="prob-track"><div class="prob-fill" style="width:${(p*100).toFixed(1)}%"></div><div class="prob-thumb" style="left:${(p*100).toFixed(1)}%"></div></div></div>`;}
function renderMatchups(data,week){const grid=$("matchup-grid"),empty=$("empty-state");grid.innerHTML="";const groups=new Map();for(const m of data||[]){if(m.matchup_id==null)continue;const k=String(m.matchup_id);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(m);}if(!groups.size){grid.hidden=true;empty.hidden=false;return;}grid.hidden=false;empty.hidden=true;for(const [,teams] of groups){if(teams.length<2)continue;const a=teams[0],b=teams[1],ta=teamInfo(a.roster_id),tb=teamInfo(b.roster_id),pa=teamProjected(ta.roster,a),pb=teamProjected(tb.roster,b);let p=winProb(pa,pb);if(a.points>b.points&&a.points!==b.points)p=Math.min(.995,Math.max(p,.5));else if(b.points>a.points)p=Math.min(.995,Math.max(1-p,.5));const card=document.createElement("article");card.className="matchup-card";card.innerHTML=`<div class="matchup-card__head"><span>Matchup ${esc(a.matchup_id)}</span><span class="matchup-card__state ${week===S.week?'is-current':''}">${week===S.week?'LIVE':week<S.week?'FINAL':'UPCOMING'}</span></div><div class="matchup-teams">${teamBlock(a,ta,pa,p,true)}<div class="vs-divider"><span>VS</span></div>${teamBlock(b,tb,pb,p,false)}</div><div class="predictor"><div class="predictor-head"><div><span class="section-kicker">FS5 Live Predictor</span><strong>${p>=.5?esc(ta.teamName):esc(tb.teamName)} favored</strong></div><span class="model-tag">Monte Carlo-style model</span></div>${probBar(p)}</div><div class="lineup-grid"><div><h3>${esc(ta.teamName)} <small>Starting lineup</small></h3>${(a.starters||[]).map(id=>playerRow(id,true)).join("")||'<p class="muted">No starters supplied.</p>'}</div><div><h3>${esc(tb.teamName)} <small>Starting lineup</small></h3>${(b.starters||[]).map(id=>playerRow(id,true)).join("")||'<p class="muted">No starters supplied.</p>'}</div></div><details class="bench-details"><summary>View benches</summary><div class="lineup-grid"><div>${(a.players||[]).filter(id=>!(a.starters||[]).includes(id)).map(id=>playerRow(id,false)).join("")||'<p class="muted">No bench data.</p>'}</div><div>${(b.players||[]).filter(id=>!(b.starters||[]).includes(id)).map(id=>playerRow(id,false)).join("")||'<p class="muted">No bench data.</p>'}</div></div></details>`;grid.appendChild(card);}
}
function teamBlock(m,t,p,prob,left){const pct=left?prob:1-prob;return `<div class="matchup-team ${m.points>0?'':''}"><div class="team-identity"><img class="team-avatar" src="${esc(t.avatar)}" alt="" onerror="this.src='/artwork/logo.png'"><div><h3>${esc(t.teamName)}</h3><span>${esc(t.account)}</span><small>Record ${t.record.wins}-${t.record.losses}-${t.record.ties} · ${fmt(t.record.pf)} PF</small></div></div><div class="score-box"><strong>${fmt(m.points)}</strong><span>Proj. ${fmt(p.projected)}</span></div></div>`;}
function showPlayer(id){const p=player(id),cur=currentFor(id),proj=projectionFor(id),stats=S.stats[id]||{};$("player-modal-content").innerHTML=`<div class="player-detail"><img class="player-detail__image" src="${esc(pimg(id))}" alt="" onerror="this.src='/artwork/logo.png'"><div><p class="section-kicker">Sleeper Player Profile</p><h2 id="player-modal-name">${esc((p.first_name||"")+" "+(p.last_name||""))}</h2><p class="player-detail__team">${esc(p.position||p.fantasy_positions?.join(', ')||"")} · ${esc(p.team||"Free Agent")}</p><div class="player-detail__chips"><span>${fmt(cur)} current</span><span>${fmt(proj)} projected</span>${p.injury_status?`<span>${esc(p.injury_status)}</span>`:""}</div><dl class="player-meta"><div><dt>Age</dt><dd>${esc(p.age??"—")}</dd></div><div><dt>Experience</dt><dd>${esc(p.years_exp??"—")} yrs</dd></div><div><dt>College</dt><dd>${esc(p.college||"—")}</dd></div><div><dt>Number</dt><dd>${esc(p.number??"—")}</dd></div><div><dt>Status</dt><dd>${esc(p.status||"—")}</dd></div><div><dt>Depth Chart</dt><dd>${esc(p.depth_chart_position??"—")}</dd></div></dl><pre class="player-stats">${esc(JSON.stringify(stats,null,2))}</pre></div></div>`;$("player-modal").hidden=false;$("player-modal").setAttribute("aria-hidden","false");}
document.addEventListener("click",e=>{const b=e.target.closest("[data-player]");if(b)showPlayer(b.dataset.player);if(e.target.closest("[data-close-player]")){$("player-modal").hidden=true;$ ("player-modal").setAttribute("aria-hidden","true");}});
async function loadWeek(week){$("matchup-grid").setAttribute("aria-busy","true");try{const seasonType=week>14?"post":"regular";const apiWeek=week>14?week-14:week;const [matchups,stats,projections]=await Promise.all([api(`/league/${LEAGUE_ID}/matchups/${week}`),dataApi(`/stats/nfl/${seasonType}/${SEASON}/${apiWeek}`),dataApi(`/projections/nfl/${seasonType}/${SEASON}/${apiWeek}`)]);S.selected=week;S.matchups=matchups||[];S.stats=stats||{};S.projections=projections||{};renderMatchups(S.matchups,week);$("week-context").textContent=`${week===S.week?'Current week · live scoring + projections':'2026 season · historical matchup'} · auto refresh every 45 seconds`;$("live-status").textContent=week===S.week?'Live · Sleeper connected':'Historical week';$("live-status").className='live-status '+(week===S.week?'is-live':'');}catch(e){console.error(e);$("live-status").textContent='Sleeper data error';$("live-status").className='live-status is-error';$("week-context").textContent='Unable to load this week. Try Refresh.';}$("matchup-grid").setAttribute("aria-busy","false");}
async function init(){try{const [league,state,rosters,users,players,schedule]=await Promise.all([api(`/league/${LEAGUE_ID}`),api('/state/nfl'),api(`/league/${LEAGUE_ID}/rosters`),api(`/league/${LEAGUE_ID}/users`),api('/players/nfl'),fetch('https://api.sleeper.app/schedule/nfl/regular/2026',{cache:'no-store'}).then(r=>r.ok?r.json():[])]);S.league=league;S.scoring=league.scoring_settings||{};S.week=Number(state.display_week||state.week||1);S.selected=S.week;S.rosters=rosters||[];S.users=users||[];S.players=players||{};S.schedule=schedule||[];buildTeams();renderRanks();const sel=$("week-select");for(let w=1;w<=17;w++){const o=document.createElement('option');o.value=w;o.textContent=`Week ${w}`;sel.appendChild(o);}sel.disabled=false;sel.value=S.week;await loadWeek(S.week);}catch(e){console.error(e);$("live-status").textContent='Unable to connect to Sleeper';$("live-status").className='live-status is-error';$("week-context").textContent='Refresh after confirming the site can reach Sleeper.';}}
$("week-select").addEventListener('change',e=>loadWeek(Number(e.target.value)));$("refresh-button").addEventListener('click',()=>loadWeek(S.selected||S.week));setInterval(()=>{if(S.selected===S.week)loadWeek(S.week);},REFRESH_MS);init();
})();
