/* Derived from every completed Vault bowl matchup. Artwork is optional. */
window.FS5_LOCKER_AWARDS = [
  {"owner":"Bailey","season":2025,"bowl":"The Crosby Studios Bowl","round":"Fifth Place Game","art":"../vault/brackets/artwork/2025/F5.png","team":"FS5 PENITENTIARY","score":103.88,"opponent":"Georgassic Park","opponentScore":84},
  {"owner":"Brycen","season":2025,"bowl":"First Round","round":"First Round","art":null,"team":"Merry Christmas","score":134.24,"opponent":"ROUGH DRAFT","opponentScore":115.08},
  {"owner":"Chris","season":2025,"bowl":"Totino's Pizza Roll Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/CS1.png","team":"Im So Brocked Up Right Now","score":136.2,"opponent":"Merry Christmas","opponentScore":84.42},
  {"owner":"Cody","season":2025,"bowl":"The MR Memorial Bowl","round":"Last Place Game","art":"../vault/brackets/artwork/2025/F11.png","team":"Atlanta Nitro Hawgs","score":117.42,"opponent":"ROUGH DRAFT","opponentScore":102},
  {"owner":"Ethan","season":2025,"bowl":"Brycen Shut the Fuck Up Bowl","round":"Consolation Championship","art":"../vault/brackets/artwork/2025/F7.png","team":"Gallon of Allen","score":116.78,"opponent":"Im So Brocked Up Right Now","opponentScore":111.32},
  {"owner":"Ethan","season":2025,"bowl":"The Disco Feeler Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/CS2.png","team":"Gallon of Allen","score":98.3,"opponent":"Armory Road Trucks","opponentScore":62.78},
  {"owner":"Jordan","season":2025,"bowl":"The City of Homes Bowl","round":"Championship","art":"../vault/brackets/artwork/2025/F1.png","team":"The Rome Man Empire","score":143.86,"opponent":"Certified Pipers Association","opponentScore":103.5},
  {"owner":"Jordan","season":2025,"bowl":"The R.A.N.D.O.M Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/PS1.png","team":"The Rome Man Empire","score":141.4,"opponent":"Pete and His Dirty Dawgs","opponentScore":138.18},
  {"owner":"Matthew","season":2025,"bowl":"The Bloodbath Bowl","round":"First Round","art":"../vault/brackets/artwork/2025/PQ2.png","team":"The Brown Mahomos","score":124.76,"opponent":"FS5 PENITENTIARY","opponentScore":123.7},
  {"owner":"Max","season":2025,"bowl":"The Jordan Lynch Super Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/PS2.png","team":"Certified Pipers Association","score":150.5,"opponent":"The Brown Mahomos","opponentScore":93.44},
  {"owner":"Mike","season":2025,"bowl":"First Round","round":"First Round","art":null,"team":"Armory Road Trucks","score":138.78,"opponent":"Atlanta Nitro Hawgs","opponentScore":109.8},
  {"owner":"Mike","season":2025,"bowl":"The Pierogi Bowl","round":"Ninth Place Game","art":"../vault/brackets/artwork/2025/F9.png","team":"Armory Road Trucks","score":113.88,"opponent":"Merry Christmas","opponentScore":79.74},
  {"owner":"Will","season":2025,"bowl":"Battle of the Bulge","round":"First Round","art":"../vault/brackets/artwork/2025/PQ1.png","team":"Pete and His Dirty Dawgs","score":127.64,"opponent":"Georgassic Park","opponentScore":110.9},
  {"owner":"Will","season":2025,"bowl":"The Bronze Chair Bowl","round":"Third Place Game","art":"../vault/brackets/artwork/2025/F3.png","team":"Pete and His Dirty Dawgs","score":137.18,"opponent":"The Brown Mahomos","opponentScore":92.12},
  {"owner":"Bailey","season":2024,"bowl":"The Crosby Studios Bowl","round":"Fifth Place Game","art":"../vault/brackets/artwork/2024/F5.png","team":"Aubrey Road","score":134.82,"opponent":"BPT-MPB","opponentScore":93.78},
  {"owner":"Cody","season":2024,"bowl":"First Round","round":"First Round","art":null,"team":"Atlanta Nitro Hawgs","score":125.8,"opponent":"The Home Deebo","opponentScore":105.74},
  {"owner":"Cody","season":2024,"bowl":"The Pierogi Bowl","round":"Ninth Place Game","art":"../vault/brackets/artwork/2024/F9.png","team":"Atlanta Nitro Hawgs","score":154.24,"opponent":"Talladerrick Nights","opponentScore":123.58},
  {"owner":"Ethan","season":2024,"bowl":"The Disco Feeler Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/CS2.png","team":"JMFA The Empire Hitsticks Back","score":135.08,"opponent":"Atlanta Nitro Hawgs","opponentScore":118.46},
  {"owner":"Ethan","season":2024,"bowl":"The Edge Bowl","round":"Consolation Championship","art":"../vault/brackets/artwork/2024/F7.png","team":"JMFA The Empire Hitsticks Back","score":145.82,"opponent":"The Stroud Boys","opponentScore":94.4},
  {"owner":"Keith","season":2024,"bowl":"The City of Homes Bowl","round":"Championship","art":"../vault/brackets/artwork/2024/F1.png","team":"COUNT DRAFTULA","score":154.96,"opponent":"Pete and His Dawgs","opponentScore":134.28},
  {"owner":"Keith","season":2024,"bowl":"The R.A.N.D.O.M Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/PS1.png","team":"COUNT DRAFTULA","score":143.02,"opponent":"Armory Road Trucks","opponentScore":125.08},
  {"owner":"Matthew","season":2024,"bowl":"First Round","round":"First Round","art":null,"team":"The Stroud Boys","score":123.94,"opponent":"Mikes Financial Advisor","opponentScore":99.54},
  {"owner":"Matthew","season":2024,"bowl":"Totino's Pizza Roll Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/CS1.png","team":"The Stroud Boys","score":129.56,"opponent":"Talladerrick Nights","opponentScore":108.74},
  {"owner":"Max","season":2024,"bowl":"The MR Memorial Bowl","round":"Last Place Game","art":"../vault/brackets/artwork/2024/F11.png","team":"Mikes Financial Advisor","score":129.68,"opponent":"The Home Deebo","opponentScore":81.36},
  {"owner":"Mike","season":2024,"bowl":"Battle of the Bulge","round":"First Round","art":null,"team":"Armory Road Trucks","score":172.04,"opponent":"BPT-MPB","opponentScore":154.68},
  {"owner":"Mike","season":2024,"bowl":"The Bronze Chair Bowl","round":"Third Place Game","art":"../vault/brackets/artwork/2024/F3.png","team":"Armory Road Trucks","score":178.18,"opponent":"Raven Bros Circus","opponentScore":109.42},
  {"owner":"Will","season":2024,"bowl":"The Bloodbath Bowl","round":"First Round","art":null,"team":"Pete and His Dawgs","score":137.48,"opponent":"Aubrey Road","opponentScore":101.56},
  {"owner":"Will","season":2024,"bowl":"The Jordan Lynch Super Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/PS2.png","team":"Pete and His Dawgs","score":150.32,"opponent":"Raven Bros Circus","opponentScore":139.78},
  {"owner":"Bailey","season":2023,"bowl":"First Round","round":"First Round","art":null,"team":"McGriddy Twins","score":113.42,"opponent":"Jackson Fan Account A New Hope ","opponentScore":86.64},
  {"owner":"Brycen","season":2023,"bowl":"Championship","round":"Championship","art":null,"team":"Free ChiefsAholic","score":140.3,"opponent":"Mark of the Beasts","opponentScore":129.98},
  {"owner":"Brycen","season":2023,"bowl":"First Round","round":"First Round","art":null,"team":"Free ChiefsAholic","score":102.3,"opponent":"The Running Backs","opponentScore":89.18},
  {"owner":"Brycen","season":2023,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Free ChiefsAholic","score":112.2,"opponent":"Tuas Concussions One Kupp","opponentScore":108.72},
  {"owner":"Chris","season":2023,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Tuas Concussions One Kupp","score":170.88,"opponent":"Pompano Mokes","opponentScore":103.4},
  {"owner":"David","season":2023,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"The NightAmon Cometh","score":87.28,"opponent":"The PissDawgs","opponentScore":83.2},
  {"owner":"David","season":2023,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The NightAmon Cometh","score":151.9,"opponent":"McGriddy Twins","opponentScore":135.06},
  {"owner":"Ethan","season":2023,"bowl":"The Malcolm Rhodes Memorial Bowl","round":"Last Place Game","art":null,"team":"Jackson Fan Account A New Hope ","score":145.84,"opponent":"Vick's Dumb Bitches","opponentScore":121.06},
  {"owner":"Jordan","season":2023,"bowl":"First Round","round":"First Round","art":null,"team":"Mark of the Beasts","score":152.12,"opponent":"Atlanta Nitro Hawgs","opponentScore":85.64},
  {"owner":"Jordan","season":2023,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Mark of the Beasts","score":121.34,"opponent":"Pompano Mokes","opponentScore":108.6},
  {"owner":"Keith","season":2023,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Plague Dr draft","score":109.26,"opponent":"McGriddy Twins","opponentScore":79.78},
  {"owner":"Matthew","season":2023,"bowl":"First Round","round":"First Round","art":null,"team":"The PissDawgs","score":105.26,"opponent":"Vick's Dumb Bitches","opponentScore":103.22},
  {"owner":"Matthew","season":2023,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The PissDawgs","score":143.22,"opponent":"Plague Dr draft","opponentScore":109.48},
  {"owner":"Mike","season":2023,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"The Running Backs","score":108.6,"opponent":"Atlanta Nitro Hawgs","opponentScore":101.82},
  {"owner":"Brycen","season":2022,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"The Trophy Breakers","score":131.36,"opponent":"The Many St Browns of Newnan","opponentScore":79.08},
  {"owner":"Chris","season":2022,"bowl":"First Round","round":"First Round","art":null,"team":"The Home Deebo","score":137.5,"opponent":"JMFA Revenge of Dairy Sanders","opponentScore":134.14},
  {"owner":"Chris","season":2022,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The Home Deebo","score":121.66,"opponent":"The Many St Browns of Newnan","opponentScore":118.7},
  {"owner":"David","season":2022,"bowl":"First Round","round":"First Round","art":null,"team":"Moorbius","score":134,"opponent":"The Ayahuascas","opponentScore":85.84},
  {"owner":"David","season":2022,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Moorbius","score":117.78,"opponent":"The Street Vendors","opponentScore":95.72},
  {"owner":"Ethan","season":2022,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"JMFA Revenge of Dairy Sanders","score":114.82,"opponent":"Waddle House","opponentScore":111.4},
  {"owner":"Keith","season":2022,"bowl":"Championship","round":"Championship","art":null,"team":"Dr draft","score":93.5,"opponent":"The Home Deebo","opponentScore":83.58},
  {"owner":"Keith","season":2022,"bowl":"First Round","round":"First Round","art":null,"team":"Dr draft","score":161.2,"opponent":"Waddle House","opponentScore":138.4},
  {"owner":"Keith","season":2022,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Dr draft","score":92.16,"opponent":"The Trophy Breakers","opponentScore":83.18},
  {"owner":"Matthew","season":2022,"bowl":"The Malcolm Rhodes Memorial Bowl","round":"Last Place Game","art":null,"team":"The Ayahuascas","score":125.76,"opponent":"JT Wills Certified Lover Boy","opponentScore":100.48},
  {"owner":"Mike","season":2022,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Maximum Brutality","score":126.2,"opponent":"Vick's Dogs","opponentScore":123.28},
  {"owner":"Mike","season":2022,"bowl":"First Round","round":"First Round","art":null,"team":"Maximum Brutality","score":116.58,"opponent":"JT Wills Certified Lover Boy","opponentScore":100.44},
  {"owner":"Mike","season":2022,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Maximum Brutality","score":144.2,"opponent":"The Street Vendors","opponentScore":125.7},
  {"owner":"Will","season":2022,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Vick's Dogs","score":125.66,"opponent":"Moorbius","opponentScore":113.86},
  {"owner":"Chris","season":2021,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Unsolicited Dak Pics","score":145.84,"opponent":"JMFA Episode II Attack of CMC","opponentScore":132.76},
  {"owner":"Chris","season":2021,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Unsolicited Dak Pics","score":113.1,"opponent":"Davy Jones Locker Room","opponentScore":91.44},
  {"owner":"Cody","season":2021,"bowl":"The Malcolm Rhodes Memorial Bowl","round":"Last Place Game","art":null,"team":"Clean Brycen and The Girls","score":122.92,"opponent":"Terry on the Very Bottom","opponentScore":117.66},
  {"owner":"David","season":2021,"bowl":"First Round","round":"First Round","art":null,"team":"Indiaaron Jones","score":110.94,"opponent":"Alvin and the Airheads","opponentScore":77.38},
  {"owner":"David","season":2021,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Indiaaron Jones","score":91.36,"opponent":"Vick's Dogs","opponentScore":82.7},
  {"owner":"Ethan","season":2021,"bowl":"First Round","round":"First Round","art":null,"team":"JMFA Episode II Attack of CMC","score":134.6,"opponent":"Clean Brycen and The Girls","opponentScore":90.68},
  {"owner":"Ethan","season":2021,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"JMFA Episode II Attack of CMC","score":149.72,"opponent":"Maximum Brutality","opponentScore":80.14},
  {"owner":"Jordan","season":2021,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Men of the Hunt","score":146.08,"opponent":"Indiaaron Jones","opponentScore":127.16},
  {"owner":"Keith","season":2021,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Mr Draft","score":123.7,"opponent":"Alvin and the Airheads","opponentScore":120.64},
  {"owner":"Matthew","season":2021,"bowl":"First Round","round":"First Round","art":null,"team":"Davy Jones Locker Room","score":124.84,"opponent":"Terry on the Very Bottom","opponentScore":120.04},
  {"owner":"Max","season":2021,"bowl":"Championship","round":"Championship","art":null,"team":"Mikes Brakes","score":138.82,"opponent":"Men of the Hunt","opponentScore":85.36},
  {"owner":"Max","season":2021,"bowl":"First Round","round":"First Round","art":null,"team":"Mikes Brakes","score":113.32,"opponent":"Mr Draft","opponentScore":112.1},
  {"owner":"Max","season":2021,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Mikes Brakes","score":160.68,"opponent":"Vick's Dogs","opponentScore":118.98},
  {"owner":"Mike","season":2021,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Maximum Brutality","score":134.3,"opponent":"Davy Jones Locker Room","opponentScore":108.68},
  {"owner":"Bailey","season":2020,"bowl":"The Malcolm Rhodes Memorial Bowl","round":"Last Place Game","art":null,"team":"Underdogs","score":141.34,"opponent":"Deshaun Mustard","opponentScore":128.26},
  {"owner":"Brycen","season":2020,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Kareem n The Fever Dream","score":131.46,"opponent":"Davy Jones Locker Room","opponentScore":113.2},
  {"owner":"Brycen","season":2020,"bowl":"First Round","round":"First Round","art":null,"team":"Kareem n The Fever Dream","score":104.54,"opponent":"Deshaun Mustard","opponentScore":102.36},
  {"owner":"Brycen","season":2020,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Kareem n The Fever Dream","score":105.52,"opponent":"Vape Lords","opponentScore":103.54},
  {"owner":"Cody","season":2020,"bowl":"First Round","round":"First Round","art":null,"team":"The Flying Dutchmen","score":149.72,"opponent":"Vick's Dogs","opponentScore":101.74},
  {"owner":"Cody","season":2020,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The Flying Dutchmen","score":150.32,"opponent":"Mr Auto Draft","opponentScore":98.85},
  {"owner":"David","season":2020,"bowl":"Championship","round":"Championship","art":null,"team":"The Crosby Show","score":104.5,"opponent":"The Flying Dutchmen","opponentScore":103.12},
  {"owner":"David","season":2020,"bowl":"First Round","round":"First Round","art":null,"team":"The Crosby Show","score":159.72,"opponent":"Jackson Mahomes Fan Account","opponentScore":94.32},
  {"owner":"David","season":2020,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The Crosby Show","score":149.46,"opponent":"Maximum Brutality","opponentScore":118.14},
  {"owner":"Keith","season":2020,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Mr Auto Draft","score":159.24,"opponent":"Maximum Brutality","opponentScore":156.64},
  {"owner":"Matthew","season":2020,"bowl":"First Round","round":"First Round","art":null,"team":"Davy Jones Locker Room","score":124.54,"opponent":"Underdogs","opponentScore":110.12},
  {"owner":"Matthew","season":2020,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Davy Jones Locker Room","score":152.74,"opponent":"Congrats David","opponentScore":101.2},
  {"owner":"Max","season":2020,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Congrats David","score":202.66,"opponent":"Vape Lords","opponentScore":90.28},
  {"owner":"Will","season":2020,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Vick's Dogs","score":133.06,"opponent":"Jackson Mahomes Fan Account","opponentScore":117.42},
  {"owner":"Brycen","season":2019,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Reek Havoc","score":116.16,"opponent":"Mr Auto Draft","opponentScore":109.16},
  {"owner":"Chris","season":2019,"bowl":"First Round","round":"First Round","art":null,"team":"Vape Lords","score":156.4,"opponent":"Mr Auto Draft","opponentScore":140.8},
  {"owner":"Chris","season":2019,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Vape Lords","score":110.64,"opponent":"Vick's Dogs","opponentScore":69.1},
  {"owner":"Cody","season":2019,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Beats by Deandre","score":115.44,"opponent":"Davy Jones Locker Room","opponentScore":111.2},
  {"owner":"David","season":2019,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"A Song of Matty Ice and Fire","score":155.16,"opponent":"Recyclables","opponentScore":90.02},
  {"owner":"Jordan","season":2019,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"The Breakfast Chubb","score":118.06,"opponent":"Beats by Deandre","opponentScore":95.36},
  {"owner":"Jordan","season":2019,"bowl":"First Round","round":"First Round","art":null,"team":"The Breakfast Chubb","score":121.68,"opponent":"Recyclables","opponentScore":113.04},
  {"owner":"Jordan","season":2019,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The Breakfast Chubb","score":200.48,"opponent":"Lutz get to it to it to it","opponentScore":144.62},
  {"owner":"Matthew","season":2019,"bowl":"First Round","round":"First Round","art":null,"team":"Davy Jones Locker Room","score":102.24,"opponent":"A Song of Matty Ice and Fire","opponentScore":90.52},
  {"owner":"Matthew","season":2019,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Davy Jones Locker Room","score":150.92,"opponent":"Lutz get to it to it to it","opponentScore":98.66},
  {"owner":"Max","season":2019,"bowl":"Championship","round":"Championship","art":null,"team":"Double Dawgs","score":132.42,"opponent":"Maximum Brutality","opponentScore":107.24},
  {"owner":"Max","season":2019,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Double Dawgs","score":160.98,"opponent":"Vick's Dogs","opponentScore":108.28},
  {"owner":"Mike","season":2019,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Maximum Brutality","score":139.9,"opponent":"Vape Lords","opponentScore":139.82},
  {"owner":"Will","season":2019,"bowl":"First Round","round":"First Round","art":null,"team":"Vick's Dogs","score":123.96,"opponent":"Reek Havoc","opponentScore":90.94},
  {"owner":"Brycen","season":2018,"bowl":"Championship","round":"Championship","art":null,"team":"King Goffrey","score":129.36,"opponent":"Maximum Brutality","opponentScore":106.16},
  {"owner":"Brycen","season":2018,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"King Goffrey","score":157.04,"opponent":"Golden Taint","opponentScore":143.48},
  {"owner":"Chris","season":2018,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Vape Lords","score":92.46,"opponent":"Captain Kirk","opponentScore":85.38},
  {"owner":"Chris","season":2018,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Vape Lords","score":102.88,"opponent":"zea pakkk","opponentScore":100.24},
  {"owner":"David","season":2018,"bowl":"First Round","round":"First Round","art":null,"team":"Captain Kirk","score":92.14,"opponent":"kkk","opponentScore":82.64},
  {"owner":"David","season":2018,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Captain Kirk","score":116.82,"opponent":"The Quintorris Bless 'Em's","opponentScore":116.46},
  {"owner":"Ethan","season":2018,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"The Quintorris Bless 'Em's","score":121.6,"opponent":"zea pakkk","opponentScore":108.88},
  {"owner":"Jordan","season":2018,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"The Breakfast Chubb","score":84.98,"opponent":"kkk","opponentScore":76.5},
  {"owner":"Matthew","season":2018,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Christs Crusaders","score":84.24,"opponent":"Matty Twice","opponentScore":83.82},
  {"owner":"Mike","season":2018,"bowl":"First Round","round":"First Round","art":null,"team":"Maximum Brutality","score":149.7,"opponent":"Matty Twice","opponentScore":113.84},
  {"owner":"Mike","season":2018,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Maximum Brutality","score":134.34,"opponent":"Vick's Dogs","opponentScore":103.44},
  {"owner":"Will","season":2018,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Vick's Dogs","score":144.34,"opponent":"Golden Taint","opponentScore":131.9},
  {"owner":"Bailey","season":2017,"bowl":"Championship","round":"Championship","art":null,"team":"Dirty Matt and The Birds","score":114.18,"opponent":"Vick's Dogs","opponentScore":45.72},
  {"owner":"Bailey","season":2017,"bowl":"First Round","round":"First Round","art":null,"team":"Dirty Matt and The Birds","score":100.98,"opponent":"kkk","opponentScore":93.16},
  {"owner":"Bailey","season":2017,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Dirty Matt and The Birds","score":96.02,"opponent":"The Brown Note","opponentScore":92.28},
  {"owner":"Chris","season":2017,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"Hate","score":115.64,"opponent":"Scam Newton","opponentScore":74.7},
  {"owner":"Ethan","season":2017,"bowl":"First Round","round":"First Round","art":null,"team":"Joseph Smith","score":100.54,"opponent":"Scam Newton","opponentScore":82.48},
  {"owner":"Ethan","season":2017,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Joseph Smith","score":84.94,"opponent":"Dak and Milds","opponentScore":57.56},
  {"owner":"Matthew","season":2017,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Le'veon Smells","score":97.5,"opponent":"Joseph Smith","opponentScore":56.4},
  {"owner":"Matthew","season":2017,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Le'veon Smells","score":97.66,"opponent":"Golden Taint","opponentScore":85.92},
  {"owner":"Mike","season":2017,"bowl":"First Round","round":"First Round","art":null,"team":"Maximum Brutality","score":114.26,"opponent":"Dea Paak","opponentScore":97.64},
  {"owner":"Mike","season":2017,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Maximum Brutality","score":73.06,"opponent":"The Brown Note","opponentScore":49.62},
  {"owner":"Will","season":2017,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Vick's Dogs","score":104.26,"opponent":"Maximum Brutality","opponentScore":92.84},
  {"owner":"Brycen","season":2016,"bowl":"First Round","round":"First Round","art":null,"team":"The Clit Commanders","score":98.06,"opponent":"Natty Ice","opponentScore":62.72},
  {"owner":"Chris","season":2016,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"Hate","score":95.28,"opponent":"Mattyice8","opponentScore":48.1},
  {"owner":"Jordan","season":2016,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Deez Nuts","score":155.5,"opponent":"The Clit Commanders","opponentScore":101.46},
  {"owner":"Keith","season":2016,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"kkk","score":71.4,"opponent":"I love anal 69 in my butt","opponentScore":55.46},
  {"owner":"Keith","season":2016,"bowl":"First Round","round":"First Round","art":null,"team":"kkk","score":89.02,"opponent":"Hate","opponentScore":77.2},
  {"owner":"Keith","season":2016,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"kkk","score":120.64,"opponent":"Tom deflated my balls","opponentScore":53.38},
  {"owner":"Mike","season":2016,"bowl":"First Round","round":"First Round","art":null,"team":"I love anal 69 in my butt","score":81.04,"opponent":"Mattyice8","opponentScore":70.74},
  {"owner":"Mike","season":2016,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"I love anal 69 in my butt","score":75.58,"opponent":"Ronalbro's","opponentScore":52.04},
  {"owner":"Will","season":2016,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Vick's Dogs","score":101.48,"opponent":"Natty Ice","opponentScore":77.84},
  {"owner":"Chris","season":2015,"bowl":"First Round","round":"First Round","art":null,"team":"Hate","score":137.04,"opponent":"Devonta Freeman","opponentScore":133.9},
  {"owner":"Chris","season":2015,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"Hate","score":103,"opponent":"Natty Ice","opponentScore":84.76},
  {"owner":"Cody","season":2015,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Will Meyer","score":68.42,"opponent":"Vick's Dogs","opponentScore":51.1},
  {"owner":"Jordan","season":2015,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Devonta Freeman","score":110.72,"opponent":"The Clit Commanders","opponentScore":76.98},
  {"owner":"Keith","season":2015,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"kkk","score":75.96,"opponent":"Mattyice8","opponentScore":70.54},
  {"owner":"Keith","season":2015,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"kkk","score":51,"opponent":"Vick's Dogs","opponentScore":44.4},
  {"owner":"Matthew","season":2015,"bowl":"First Round","round":"First Round","art":null,"team":"Mattyice8","score":112.86,"opponent":"Mike Vick in a box","opponentScore":73.84},
  {"owner":"Matthew","season":2015,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Mattyice8","score":75.2,"opponent":"Will Meyer","opponentScore":54.94},
  {"owner":"Will","season":2015,"bowl":"First Round","round":"First Round","art":null,"team":"Vick's Dogs","score":99.2,"opponent":"Ronalbro's","opponentScore":63.04},
  {"owner":"Brycen","season":2014,"bowl":"First Round","round":"First Round","art":null,"team":"How I Lucked Your Mother","score":95.28,"opponent":"Tickle me Al-Mo","opponentScore":55.92},
  {"owner":"Chris","season":2014,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"Hate","score":80.4,"opponent":"Mattyice8","opponentScore":73.26},
  {"owner":"Cody","season":2014,"bowl":"Fifth Place Game","round":"Fifth Place Game","art":null,"team":"Tickle me Al-Mo","score":77.22,"opponent":"Insane Clowney Posse","opponentScore":73.96},
  {"owner":"David","season":2014,"bowl":"First Round","round":"First Round","art":null,"team":"Natty Ice","score":91.4,"opponent":"Mattyice8","opponentScore":47.24},
  {"owner":"David","season":2014,"bowl":"Ninth Place Game","round":"Ninth Place Game","art":null,"team":"Natty Ice","score":122.9,"opponent":"Ronalbro's","opponentScore":63.8},
  {"owner":"Max","season":2014,"bowl":"First Round","round":"First Round","art":null,"team":"The Startled Penguins","score":98.2,"opponent":"Insane Clowney Posse","opponentScore":90.52},
  {"owner":"Max","season":2014,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"The Startled Penguins","score":91.16,"opponent":"How I Lucked Your Mother","opponentScore":76},
  {"owner":"Mike","season":2014,"bowl":"Championship","round":"Championship","art":null,"team":"cougars","score":100.04,"opponent":"Dirty birds","opponentScore":90.34},
  {"owner":"Mike","season":2014,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"cougars","score":113.12,"opponent":"The Startled Penguins","opponentScore":85.94},
  {"owner":"Will","season":2014,"bowl":"First Round","round":"First Round","art":null,"team":"Vick's Dogs","score":94.4,"opponent":"Hate","opponentScore":68.68},
  {"owner":"Will","season":2014,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Vick's Dogs","score":102.72,"opponent":"Ronalbro's","opponentScore":56.18},
  {"owner":"Bailey","season":2013,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Wangles","score":91.18,"opponent":"Wilfredo's Pasta","opponentScore":58.34},
  {"owner":"Brycen","season":2013,"bowl":"Championship","round":"Championship","art":null,"team":"David Sucks Wang","score":98.28,"opponent":"Dirty birds","opponentScore":65.32},
  {"owner":"Brycen","season":2013,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"David Sucks Wang","score":114.62,"opponent":"Squad","opponentScore":100.58},
  {"owner":"David","season":2013,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Natty Ice","score":96.94,"opponent":"Wangles","opponentScore":66.58},
  {"owner":"David","season":2013,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Natty Ice","score":83.2,"opponent":"Meyeahs","opponentScore":60.04},
  {"owner":"Mike","season":2013,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"cougars","score":130.84,"opponent":"Squad","opponentScore":95.08},
  {"owner":"Will","season":2013,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"Wilfredo's Pasta","score":76.5,"opponent":"Meyeahs","opponentScore":72.66},
  {"owner":"Chris","season":2012,"bowl":"Last Place Game","round":"Last Place Game","art":null,"team":"Squad","score":101.14,"opponent":"Green Eggs and CAM","opponentScore":81.12},
  {"owner":"Jordan","season":2012,"bowl":"Third Place Game","round":"Third Place Game","art":null,"team":"LynchMob","score":101.38,"opponent":"Qui","opponentScore":86.26},
  {"owner":"Max","season":2012,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"The Startled Penguins","score":119.58,"opponent":"Qui","opponentScore":118.88},
  {"owner":"Will","season":2012,"bowl":"Consolation Championship","round":"Consolation Championship","art":null,"team":"Saving Rex Ryan","score":156.26,"opponent":"You suck more than my GF","opponentScore":81.52},
  {"owner":"Will","season":2012,"bowl":"Semifinal","round":"Semifinal","art":null,"team":"Saving Rex Ryan","score":117.26,"opponent":"Squad","opponentScore":112.24}
];
