/* Derived from named Vault bowls beginning in 2024, plus historical championships.
   Add display_slot: "hanging", "large", or "feature" to reserve either of the
   two oversized top-bay positions; untagged awards use the standard shelves. */
window.FS5_LOCKER_AWARDS = [
  {"owner":"Bailey","season":2025,"bowl":"The Crosby Studios Bowl","round":"Fifth Place Game","art":"../vault/brackets/artwork/2025/F5.png","team":"FS5 PENITENTIARY","score":103.88,"opponent":"Georgassic Park","opponentScore":84},
  {"owner":"Brycen","season":2025,"bowl":"First Round","round":"First Round","art":null,"team":"Merry Christmas","score":134.24,"opponent":"ROUGH DRAFT","opponentScore":115.08},
  {"owner":"Chris","season":2025,"bowl":"Totino's Pizza Roll Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/CS1.png","team":"Im So Brocked Up Right Now","score":136.2,"opponent":"Merry Christmas","opponentScore":84.42},
  {"owner":"Cody","season":2025,"bowl":"The MR Memorial Bowl","round":"Last Place Game","art":"../vault/brackets/artwork/2025/F11.png","team":"Atlanta Nitro Hawgs","score":117.42,"opponent":"ROUGH DRAFT","opponentScore":102},
  {"owner":"Ethan","season":2025,"bowl":"Brycen Shut the Fuck Up Bowl","round":"Consolation Championship","art":"../vault/brackets/artwork/2025/F7.png","team":"Gallon of Allen","score":116.78,"opponent":"Im So Brocked Up Right Now","opponentScore":111.32},
  {"owner":"Ethan","season":2025,"bowl":"The Disco Feeler Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/CS2.png","team":"Gallon of Allen","score":98.3,"opponent":"Armory Road Trucks","opponentScore":62.78},
  {"owner":"Jordan","season":2025,"bowl":"The City of Homes Bowl","round":"Championship","art":"../vault/brackets/artwork/2025/F1.png","team":"The Rome Man Empire","score":143.86,"opponent":"Certified Pipers Association","opponentScore":103.5},
  {"owner":"Jordan","season":2025,"bowl":"The R.A.N.D.O.M Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/PS1.png","team":"The Rome Man Empire","score":141.4,"opponent":"Pete and His Dirty Dawgs","opponentScore":138.18},
  {"owner":"Matthew","season":2025,"bowl":"The Bloodbath Bowl","round":"First Round","art":"../vault/brackets/artwork/2025/PQ2.png","team":"The Brown Mahomos","score":124.76,"opponent":"FS5 PENITENTIARY","opponentScore":123.7},
  {"owner":"Max","season":2025,"bowl":"The Jordan Lynch Super Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2025/PS2.png","team":"Certified Pipers Association","score":150.5,"opponent":"The Brown Mahomos","opponentScore":93.44},
  {"owner":"Mike","season":2025,"bowl":"First Round","round":"First Round","art":null,"team":"Armory Road Trucks","score":138.78,"opponent":"Atlanta Nitro Hawgs","opponentScore":109.8},
  {"owner":"Mike","season":2025,"bowl":"The Pierogi Bowl","round":"Ninth Place Game","art":"../vault/brackets/artwork/2025/F9.png","team":"Armory Road Trucks","score":113.88,"opponent":"Merry Christmas","opponentScore":79.74},
  {"owner":"Will","season":2025,"bowl":"Battle of the Bulge","round":"First Round","art":"../vault/brackets/artwork/2025/PQ1.png","team":"Pete and His Dirty Dawgs","score":127.64,"opponent":"Georgassic Park","opponentScore":110.9},
  {"owner":"Will","season":2025,"bowl":"The Bronze Chair Bowl","round":"Third Place Game","art":"../vault/brackets/artwork/2025/F3.png","team":"Pete and His Dirty Dawgs","score":137.18,"opponent":"The Brown Mahomos","opponentScore":92.12},
  {"owner":"Bailey","season":2024,"bowl":"The Crosby Studios Bowl","round":"Fifth Place Game","art":"../vault/brackets/artwork/2024/F5.png","team":"Aubrey Road","score":134.82,"opponent":"BPT-MPB","opponentScore":93.78},
  {"owner":"Cody","season":2024,"bowl":"First Round","round":"First Round","art":null,"team":"Atlanta Nitro Hawgs","score":125.8,"opponent":"The Home Deebo","opponentScore":105.74},
  {"owner":"Cody","season":2024,"bowl":"The Pierogi Bowl","round":"Ninth Place Game","art":"../vault/brackets/artwork/2024/F9.png","team":"Atlanta Nitro Hawgs","score":154.24,"opponent":"Talladerrick Nights","opponentScore":123.58},
  {"owner":"Ethan","season":2024,"bowl":"The Disco Feeler Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/CS2.png","team":"JMFA The Empire Hitsticks Back","score":135.08,"opponent":"Atlanta Nitro Hawgs","opponentScore":118.46},
  {"owner":"Ethan","season":2024,"bowl":"The Edge Bowl","round":"Consolation Championship","art":"../vault/brackets/artwork/2024/F7.png","team":"JMFA The Empire Hitsticks Back","score":145.82,"opponent":"The Stroud Boys","opponentScore":94.4},
  {"owner":"Keith","season":2024,"bowl":"The City of Homes Bowl","round":"Championship","art":"../vault/brackets/artwork/2024/F1.png","team":"COUNT DRAFTULA","score":154.96,"opponent":"Pete and His Dawgs","opponentScore":134.28},
  {"owner":"Keith","season":2024,"bowl":"The R.A.N.D.O.M Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/PS1.png","team":"COUNT DRAFTULA","score":143.02,"opponent":"Armory Road Trucks","opponentScore":125.08},
  {"owner":"Matthew","season":2024,"bowl":"First Round","round":"First Round","art":null,"team":"The Stroud Boys","score":123.94,"opponent":"Mikes Financial Advisor","opponentScore":99.54},
  {"owner":"Matthew","season":2024,"bowl":"Totino's Pizza Roll Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/CS1.png","team":"The Stroud Boys","score":129.56,"opponent":"Talladerrick Nights","opponentScore":108.74},
  {"owner":"Max","season":2024,"bowl":"The MR Memorial Bowl","round":"Last Place Game","art":"../vault/brackets/artwork/2024/F11.png","team":"Mikes Financial Advisor","score":129.68,"opponent":"The Home Deebo","opponentScore":81.36},
  {"owner":"Mike","season":2024,"bowl":"Battle of the Bulge","round":"First Round","art":null,"team":"Armory Road Trucks","score":172.04,"opponent":"BPT-MPB","opponentScore":154.68},
  {"owner":"Mike","season":2024,"bowl":"The Bronze Chair Bowl","round":"Third Place Game","art":"../vault/brackets/artwork/2024/F3.png","team":"Armory Road Trucks","score":178.18,"opponent":"Raven Bros Circus","opponentScore":109.42},
  {"owner":"Will","season":2024,"bowl":"The Bloodbath Bowl","round":"First Round","art":null,"team":"Pete and His Dawgs","score":137.48,"opponent":"Aubrey Road","opponentScore":101.56},
  {"owner":"Will","season":2024,"bowl":"The Jordan Lynch Super Bowl","round":"Semifinal","art":"../vault/brackets/artwork/2024/PS2.png","team":"Pete and His Dawgs","score":150.32,"opponent":"Raven Bros Circus","opponentScore":139.78},
  {"owner":"Brycen","season":2023,"bowl":"Championship","round":"Championship","art":null,"team":"Free ChiefsAholic","score":140.3,"opponent":"Mark of the Beasts","opponentScore":129.98},
  {"owner":"Keith","season":2022,"bowl":"Championship","round":"Championship","art":null,"team":"Dr draft","score":93.5,"opponent":"The Home Deebo","opponentScore":83.58},
  {"owner":"Max","season":2021,"bowl":"Championship","round":"Championship","art":null,"team":"Mikes Brakes","score":138.82,"opponent":"Men of the Hunt","opponentScore":85.36},
  {"owner":"David","season":2020,"bowl":"Championship","round":"Championship","art":null,"team":"The Crosby Show","score":104.5,"opponent":"The Flying Dutchmen","opponentScore":103.12},
  {"owner":"Max","season":2019,"bowl":"Championship","round":"Championship","art":null,"team":"Double Dawgs","score":132.42,"opponent":"Maximum Brutality","opponentScore":107.24},
  {"owner":"Brycen","season":2018,"bowl":"Championship","round":"Championship","art":null,"team":"King Goffrey","score":129.36,"opponent":"Maximum Brutality","opponentScore":106.16},
  {"owner":"Bailey","season":2017,"bowl":"Championship","round":"Championship","art":null,"team":"Dirty Matt and The Birds","score":114.18,"opponent":"Vick's Dogs","opponentScore":45.72},
  {"owner":"Mike","season":2014,"bowl":"Championship","round":"Championship","art":null,"team":"cougars","score":100.04,"opponent":"Dirty birds","opponentScore":90.34},
  {"owner":"Brycen","season":2013,"bowl":"Championship","round":"Championship","art":null,"team":"David Sucks Wang","score":98.28,"opponent":"Dirty birds","opponentScore":65.32}
];
